<?php

try {
} catch (\FirstException | \SecondException $e) {
	handler();
} catch (\Exception $e) {
	handler2();
}
